services:
  vrising:
    image: trueosiris/vrising
    environment:
      - TZ=Europe/Madrid
      - SERVERNAME=Vrising-TEST
    volumes:
      - type: bind
        source: /home/debianserver/vrising/server
        target: /mnt/vrising/server
      - type: bind
        source: /home/debianserver/vrising/persistentdata
        target: /mnt/vrising/persistentdata
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge
